import type { EventsQuery, ReviewRequest, OrdersQuery, PositionStatusFilter, TradesQuery } from "@/types";

export const qk = {
  authStatus: ["auth", "status"] as const,
  me: ["auth", "me"] as const,
  systemStatus: ["system", "status"] as const,
  systemConfig: ["system", "config"] as const,
  events: (q: EventsQuery) => ["events", q] as const,
  eventsAll: ["events"] as const,
  dashboard: ["dashboard"] as const,
  dashboardSummary: ["dashboard", "summary"] as const,
  dashboardPnl: (days: number) => ["dashboard", "pnl", days] as const,
  dashboardPerformance: ["dashboard", "performance"] as const,
  guide: ["guide"] as const,
  onboarding: ["guide", "onboarding"] as const,
  brokers: ["brokers"] as const,
  brokersList: ["brokers", "list"] as const,
  brokerStatus: ["brokers", "status"] as const,
  strategies: ["strategies"] as const,
  strategiesList: ["strategies", "list"] as const,
  strategyTypes: ["strategy-types"] as const,
  strategy: (id: string) => ["strategies", "detail", id] as const,
  strategyReview: (id: string) => ["strategies", "review", id] as const,
  strategyReviewDraft: (req: ReviewRequest) => ["strategies", "review-draft", req] as const,
  strategySignals: (id: string, limit: number) => ["strategies", "signals", id, limit] as const,
  orders: ["orders"] as const,
  ordersList: (q: OrdersQuery) => ["orders", "list", q] as const,
  order: (id: string) => ["orders", "detail", id] as const,
  positions: ["positions"] as const,
  positionsList: (s: PositionStatusFilter) => ["positions", "list", s] as const,
  trades: ["trades"] as const,
  tradesList: (q: TradesQuery) => ["trades", "list", q] as const,
  backtests: ["backtests"] as const,
  backtestsList: (limit: number) => ["backtests", "list", limit] as const,
  backtestReport: (id: string) => ["backtests", "report", id] as const,
  risk: ["risk"] as const,
  riskConfig: ["risk", "config"] as const,
  riskStatus: ["risk", "status"] as const,
  instruments: (search: string) => ["instruments", search] as const,
};
