"""API-facing research service: starting runs, reading reports and history, weights, sources, universes, export."""

from __future__ import annotations

import csv
import io
from collections.abc import Callable
from datetime import date, timedelta
from typing import Any

from app.core.config import Settings
from app.core.exceptions import ConflictError, NotFoundError, PermissionDeniedError, ValidationFailedError
from app.models.research import (
    ResearchAgentRun,
    ResearchRun,
    ResearchScore,
    ResearchSource,
    ResearchUniverseMember,
    ResearchWeightSet,
)
from app.models.user import User
from app.research import sessions as ses
from app.research.config import DEFAULT_WEIGHTS, validate_weights
from app.research.contracts import AGENT_LABELS, UNAVAILABLE_AGENTS, MarketContext, ResearchReport
from app.research.explain import explain_change
from app.research.pipeline import DEPTHS
from app.research.reference.nifty50 import AS_OF_NOTE, NIFTY50, UNIVERSE_NAME
from app.schemas.research import (
    AgentRunRead,
    CandidateList,
    CandidateRead,
    MarketOverview,
    ReportSummary,
    ResearchRunRead,
    ResearchSummaryRead,
    RiskView,
    RunRequest,
    ScoreHistory,
    ScorePoint,
    SectorOverview,
    SourcesView,
    TechnicalView,
    UniverseMemberRead,
    UniverseRead,
    UniverseWrite,
    WeightSetCreate,
)
from app.services.research_store import ResearchStore
from app.utils.time import utcnow

# (key, name, source_type, priority, base_url, reliability, notes, capabilities)
# capabilities = (market data, news, filings, fundamentals, derivatives): what the source COULD supply
# once an adapter exists. `connected` on the row says whether one does.
DEFAULT_SOURCES: tuple[tuple[str, str, str, int, str | None, float, str, tuple[int, ...]], ...] = (
    (
        "dhan",
        "Dhan market data",
        "MARKET_DATA_PROVIDER",
        2,
        "https://api.dhan.co",
        0.9,
        "Broker market data API. Needs credentials and a Data API subscription.",
        (1, 0, 0, 0, 1),
    ),
    (
        "zerodha",
        "Zerodha Kite market data",
        "MARKET_DATA_PROVIDER",
        2,
        "https://api.kite.trade",
        0.9,
        "Broker market data API. Needs credentials.",
        (1, 0, 0, 0, 1),
    ),
    (
        "simulated",
        "Simulated market data",
        "SIMULATED",
        3,
        None,
        0.1,
        "Synthetic test data generated by the platform. Never valid for research conclusions.",
        (1, 0, 0, 0, 0),
    ),
    (
        "nse",
        "NSE",
        "EXCHANGE",
        1,
        "https://www.nseindia.com",
        1.0,
        "Official exchange. No adapter yet; needs a permitted feed.",
        (1, 1, 1, 1, 1),
    ),
    (
        "bse",
        "BSE",
        "EXCHANGE",
        1,
        "https://www.bseindia.com",
        1.0,
        "Official exchange. No adapter yet.",
        (1, 1, 1, 1, 1),
    ),
    (
        "sebi",
        "SEBI",
        "REGULATOR",
        1,
        "https://www.sebi.gov.in",
        1.0,
        "Regulator. No adapter yet.",
        (0, 0, 1, 0, 0),
    ),
    (
        "company_ir",
        "Company investor relations and filings",
        "COMPANY_FILING",
        1,
        None,
        0.95,
        "No adapter yet.",
        (0, 1, 1, 1, 0),
    ),
    (
        "reuters",
        "Reuters",
        "NEWS_PROVIDER",
        2,
        "https://www.reuters.com",
        0.9,
        "News. Needs a licensed feed (planned phase 2).",
        (0, 1, 0, 0, 0),
    ),
    (
        "bloomberg",
        "Bloomberg",
        "NEWS_PROVIDER",
        2,
        "https://www.bloomberg.com",
        0.9,
        "News and data. Needs a licence (planned phase 2).",
        (1, 1, 0, 1, 1),
    ),
    (
        "economic_times",
        "Economic Times",
        "NEWS_PROVIDER",
        2,
        "https://economictimes.indiatimes.com",
        0.9,
        "News. RSS or a licensed feed (planned phase 2).",
        (0, 1, 0, 0, 0),
    ),
    (
        "business_standard",
        "Business Standard",
        "NEWS_PROVIDER",
        2,
        "https://www.business-standard.com",
        0.9,
        "News (planned phase 2).",
        (0, 1, 0, 0, 0),
    ),
    (
        "cnbc_tv18",
        "CNBC-TV18",
        "NEWS_PROVIDER",
        2,
        "https://www.cnbctv18.com",
        0.9,
        "News (planned phase 2).",
        (0, 1, 0, 0, 0),
    ),
    (
        "financial_express",
        "Financial Express",
        "NEWS_PROVIDER",
        2,
        "https://www.financialexpress.com",
        0.9,
        "News (planned phase 2).",
        (0, 1, 0, 0, 0),
    ),
    (
        "moneycontrol",
        "Moneycontrol",
        "FINANCIAL_PORTAL",
        2,
        "https://www.moneycontrol.com",
        0.8,
        "Financial portal (planned phase 2).",
        (0, 1, 0, 1, 0),
    ),
    (
        "screener",
        "Screener.in",
        "FINANCIAL_PORTAL",
        3,
        "https://www.screener.in",
        0.75,
        "Fundamentals and ratios. No adapter yet; check its terms before any automated use.",
        (0, 0, 0, 1, 0),
    ),
    (
        "trendlyne",
        "Trendlyne",
        "FINANCIAL_PORTAL",
        3,
        "https://trendlyne.com",
        0.75,
        "Fundamentals, shareholding and derivatives context. No adapter yet.",
        (0, 0, 0, 1, 1),
    ),
    (
        "tijori",
        "Tijori Finance",
        "FINANCIAL_PORTAL",
        3,
        "https://www.tijorifinance.com",
        0.75,
        "Company and segment data. No adapter yet.",
        (0, 0, 0, 1, 0),
    ),
    (
        "tradingview",
        "TradingView",
        "FINANCIAL_PORTAL",
        3,
        "https://www.tradingview.com",
        0.7,
        "Charting and screening. No adapter yet; redistribution is restricted.",
        (1, 0, 0, 0, 0),
    ),
    (
        "chartink",
        "Chartink",
        "FINANCIAL_PORTAL",
        3,
        "https://chartink.com",
        0.65,
        "Technical screening. No adapter yet.",
        (1, 0, 0, 0, 0),
    ),
    (
        "truedata",
        "TrueData",
        "MARKET_DATA_PROVIDER",
        2,
        "https://www.truedata.in",
        0.9,
        "Licensed market data vendor. Needs a paid subscription.",
        (1, 0, 0, 0, 1),
    ),
    (
        "global_datafeeds",
        "Global Datafeeds",
        "MARKET_DATA_PROVIDER",
        2,
        "https://globaldatafeeds.in",
        0.9,
        "Licensed market data vendor. Needs a paid subscription.",
        (1, 0, 0, 0, 1),
    ),
)
MAX_AS_OF_AGE_DAYS = 300


class ResearchService:
    def __init__(
        self, store: ResearchStore, settings: Settings, provider_name: str, starter: Callable[[str], None]
    ) -> None:
        self.store = store
        self.settings = settings
        self.provider_name = provider_name
        self._start = starter

    # ---- bootstrap ------------------------------------------------------------------------------
    async def bootstrap(self) -> None:
        """Idempotent seed data. Runs that were in flight when the process stopped are marked failed."""
        await self.store.runs.fail_orphans("Interrupted: the server restarted while this run was in progress")
        if not await self.store.weights.list_sets():
            await self.store.weights.create(
                ResearchWeightSet(
                    name="Default",
                    version=1,
                    status="ACTIVE",
                    weights=dict(DEFAULT_WEIGHTS),
                    thresholds={},
                    notes="Default weights from the research specification",
                    approved_at=utcnow(),
                )
            )
        existing = {s.key: s for s in await self.store.sources.list_sources()}
        for key, name, source_type, priority, url, reliability, notes, caps in DEFAULT_SOURCES:
            connected = (
                key == "simulated"
                or (key == "dhan" and self.settings.broker_credentials_configured(_broker("DHAN")))
                or (key == "zerodha" and self.settings.broker_credentials_configured(_broker("ZERODHA")))
            )
            if key not in existing:
                await self.store.sources.create(
                    ResearchSource(
                        key=key,
                        name=name,
                        source_type=source_type,
                        priority=priority,
                        base_url=url,
                        enabled=True,
                        connected=connected,
                        reliability_score=reliability,
                        notes=notes,
                        supports_market_data=bool(caps[0]),
                        supports_news=bool(caps[1]),
                        supports_filings=bool(caps[2]),
                        supports_fundamentals=bool(caps[3]),
                        supports_derivatives=bool(caps[4]),
                    )
                )
            elif existing[key].connected != connected and key in ("dhan", "zerodha", "simulated"):
                existing[key].connected = connected
        if not await self.store.universe.members(UNIVERSE_NAME):
            await self.store.universe.add_many(
                [
                    ResearchUniverseMember(universe=UNIVERSE_NAME, symbol=s, sector=sector, note=AS_OF_NOTE)
                    for s, _n, _t, _tick, sector in NIFTY50
                ]
            )

    # ---- runs -----------------------------------------------------------------------------------
    def _run_read(self, run: ResearchRun, agents: list[ResearchAgentRun] | None = None) -> ResearchRunRead:
        read = ResearchRunRead.model_validate(run)
        read.agents = [
            AgentRunRead.model_validate(a).model_copy(update={"label": AGENT_LABELS.get(a.agent, a.agent)})
            for a in (agents or [])
        ]
        return read

    async def create_run(self, request: RunRequest, user: User | None) -> ResearchRunRead:
        now = utcnow()
        as_of = request.as_of.astimezone(now.tzinfo) if request.as_of else now
        if as_of > now + timedelta(minutes=1):
            raise ValidationFailedError("as_of cannot be in the future")
        if (now - as_of).days > MAX_AS_OF_AGE_DAYS:
            raise ValidationFailedError(
                f"as_of cannot be more than {MAX_AS_OF_AGE_DAYS} days ago: the stored history is shorter than that"
            )
        active = await self.store.runs.active_run()
        if active is not None:
            raise ConflictError(
                f"Research run #{active.run_number} is still in progress. Wait for it to finish."
            )

        symbols: list[str] | None = None
        if request.universe == "CUSTOM":
            if not request.symbols:
                raise ValidationFailedError("Provide `symbols` for a CUSTOM universe")
            unknown = [
                s for s in request.symbols if await self.store.instruments.get_by_symbol(s, "NSE") is None
            ]
            if unknown:
                raise ValidationFailedError(
                    f"Unknown instrument(s): {', '.join(unknown)}. Add them to the instrument master first."
                )
            symbols = request.symbols
        else:
            if not await self.store.universe.members(request.universe):
                names = ", ".join(u for u, _ in await self.store.universe.universes()) or "none"
                raise ValidationFailedError(
                    f"Unknown universe '{request.universe}'. Available: {names}, CUSTOM"
                )
        weight_set = await self.store.weights.active()
        run = await self.store.runs.create(
            ResearchRun(
                run_number=await self.store.runs.next_run_number(),
                status="PENDING",
                market=request.market,
                universe=request.universe,
                research_type=request.research_type,
                depth=request.depth,
                as_of=as_of,
                is_live=abs((now - as_of).total_seconds()) < 120,
                is_synthetic=self.provider_name == "simulated",
                data_source=self.provider_name,
                weight_set_id=weight_set.id if weight_set else None,
                requested_symbols=symbols,
                created_by=user.id if user else None,
            )
        )
        agents = []
        for agent in AGENT_LABELS:
            status = (
                "NOT_AVAILABLE"
                if agent in UNAVAILABLE_AGENTS
                else (
                    "SKIPPED"
                    if (agent == "DataVerificationAgent" and not DEPTHS[request.depth]["verification"])
                    else "PENDING"
                )
            )
            agents.append(
                ResearchAgentRun(
                    run_id=run.id,
                    agent=agent,
                    status=status,
                    message=UNAVAILABLE_AGENTS.get(agent)
                    or ("Verification is skipped at Quick depth" if status == "SKIPPED" else None),
                )
            )
        for row in agents:
            await self.store.agent_runs.create(row)
        await self.store.runs.commit()  # the background task reads this row, so it must be visible before we start it
        self._start(run.id)
        return self._run_read(run, agents)

    async def list_runs(self, limit: int, offset: int) -> list[ResearchRunRead]:
        return [self._run_read(r) for r in await self.store.runs.list_recent(limit, offset)]

    async def get_run(self, run_id: str) -> ResearchRunRead:
        run = await self.store.runs.get_by_id(run_id)
        if run is None:
            raise NotFoundError("Research run not found")
        agents = sorted(
            await self.store.agent_runs.for_run(run_id),
            key=lambda a: list(AGENT_LABELS).index(a.agent) if a.agent in AGENT_LABELS else 99,
        )
        return self._run_read(run, agents)

    async def summary(self) -> ResearchSummaryRead:
        latest = await self.store.runs.latest_completed()
        active = await self.store.runs.active_run()
        return ResearchSummaryRead(
            latest_run=self._run_read(latest) if latest else None,
            active_run=await self.get_run(active.id) if active else None,
        )

    async def _resolve_run(self, run_id: str | None) -> ResearchRun | None:
        if run_id:
            run = await self.store.runs.get_by_id(run_id)
            if run is None:
                raise NotFoundError("Research run not found")
            return run
        return await self.store.runs.latest_completed()

    # ---- candidates and reports ---------------------------------------------------------------------
    async def candidates(
        self, run_id: str | None, include_unanalyzed: bool = False, **filters: Any
    ) -> CandidateList:
        run = await self._resolve_run(run_id)
        if run is None:
            return CandidateList(run=None, items=[], sectors=[], total=0)
        rows = await self.store.scores.list_for_run(run.id, **filters)
        items = [
            CandidateRead(
                rank=r.rank,
                symbol=r.symbol,
                company=r.company,
                sector=r.sector,
                stage="ANALYZED",
                price=r.price,
                change_pct=r.change_pct,
                rel_volume=r.rel_volume,
                atr_pct=r.atr_pct,
                vwap=r.vwap,
                vwap_position=r.vwap_position,
                research_score=r.research_score,
                data_confidence=r.data_confidence,
                risk_score=r.risk_score,
                coverage_pct=r.coverage_pct,
                risk_level=r.risk_level,
                direction=r.direction,
                setup_quality=r.setup_quality,
                initial_score=r.initial_score,
                warning_count=r.warning_count,
                as_of=r.as_of,
                run_id=r.run_id,
            )
            for r in rows
        ]
        if include_unanalyzed:
            for c in await self.store.candidates.list_for_run(run.id):
                if c.stage != "ANALYZED":
                    feats = c.features or {}
                    items.append(
                        CandidateRead(
                            rank=None,
                            symbol=c.symbol,
                            company=c.company,
                            sector=c.sector,
                            stage=c.stage,
                            exclusion_reason=c.exclusion_reason,
                            price=feats.get("price"),
                            change_pct=feats.get("change_pct"),
                            rel_volume=feats.get("rel_volume"),
                            atr_pct=feats.get("atr_pct"),
                            vwap=feats.get("vwap"),
                            vwap_position=feats.get("vwap_position"),
                            research_score=None,
                            data_confidence=None,
                            coverage_pct=None,
                            risk_level=None,
                            direction=feats.get("direction"),
                            setup_quality=None,
                            initial_score=c.initial_score,
                            reasons=c.reasons,
                            as_of=run.as_of,
                            run_id=run.id,
                        )
                    )
        return CandidateList(
            run=self._run_read(run),
            items=items,
            sectors=await self.store.scores.sectors(run.id),
            total=len(items),
        )

    async def candidate(self, symbol: str, run_id: str | None = None) -> CandidateRead:
        r = await self._score(symbol, run_id)
        row = await self.store.candidates.get_for_run(r.run_id, r.symbol)
        return CandidateRead(
            rank=r.rank,
            symbol=r.symbol,
            company=r.company,
            sector=r.sector,
            stage="ANALYZED",
            price=r.price,
            change_pct=r.change_pct,
            rel_volume=r.rel_volume,
            atr_pct=r.atr_pct,
            vwap=r.vwap,
            vwap_position=r.vwap_position,
            research_score=r.research_score,
            data_confidence=r.data_confidence,
            risk_score=r.risk_score,
            coverage_pct=r.coverage_pct,
            risk_level=r.risk_level,
            direction=r.direction,
            setup_quality=r.setup_quality,
            initial_score=r.initial_score,
            warning_count=r.warning_count,
            reasons=row.reasons if row else [],
            as_of=r.as_of,
            run_id=r.run_id,
        )

    async def _score(self, symbol: str, run_id: str | None) -> ResearchScore:
        score = await (
            self.store.scores.get_for_run(run_id, symbol)
            if run_id
            else self.store.scores.latest_for_symbol(symbol)
        )
        if score is None:
            raise NotFoundError(
                f"No research report for {symbol.upper()} yet. Run a research scan that includes it."
            )
        return score

    async def report(self, symbol: str, run_id: str | None = None) -> ResearchReport:
        return ResearchReport.model_validate((await self._score(symbol, run_id)).report)

    async def technical(self, symbol: str, run_id: str | None = None) -> TechnicalView:
        r = await self.report(symbol, run_id)
        return TechnicalView(
            symbol=r.symbol,
            run_id=r.run_id,
            as_of=r.as_of,
            price=r.price,
            volatility=r.volatility,
            technical=r.technical,
            levels=r.technical.levels,
        )

    async def risk(self, symbol: str, run_id: str | None = None) -> RiskView:
        r = await self.report(symbol, run_id)
        return RiskView(symbol=r.symbol, run_id=r.run_id, as_of=r.as_of, risk=r.risk, warnings=r.warnings)

    async def sources(self, symbol: str, run_id: str | None = None) -> SourcesView:
        r = await self.report(symbol, run_id)
        provenance = [
            r.technical.provenance,
            r.risk.provenance,
            r.verification.provenance,
            r.market_context.provenance,
        ]
        return SourcesView(
            symbol=r.symbol,
            run_id=r.run_id,
            sources=r.sources,
            claims=r.verification.claims,
            data_confidence=r.verification.data_confidence,
            provenance=provenance,
        )

    async def agent_trace(self, symbol: str, run_id: str | None = None) -> list[dict[str, Any]]:
        report = await self.report(symbol, run_id)
        return [a.model_dump(mode="json") for a in report.agents]

    async def history(self, symbol: str, limit: int) -> list[ReportSummary]:
        out = []
        for s in await self.store.scores.history(symbol, limit):
            run = await self.store.runs.get_by_id(s.run_id)
            out.append(
                ReportSummary(
                    run_id=s.run_id,
                    run_number=run.run_number if run else None,
                    as_of=s.as_of,
                    research_score=s.research_score,
                    data_confidence=s.data_confidence,
                    risk_score=s.risk_score,
                    direction=s.direction,
                    setup_quality=s.setup_quality,
                    risk_level=s.risk_level,
                    rank=s.rank,
                    is_synthetic=bool(run and run.is_synthetic),
                )
            )
        return out

    async def score_history(self, symbol: str, limit: int = 30) -> ScoreHistory:
        rows = list(reversed(await self.store.scores.history(symbol, limit)))  # oldest first
        if not rows:
            raise NotFoundError(f"No research history for {symbol.upper()}")
        points = [
            ScorePoint(
                run_id=r.run_id,
                as_of=r.as_of,
                research_score=r.research_score,
                data_confidence=r.data_confidence,
                risk_score=r.risk_score,
                direction=r.direction,
                risk_level=r.risk_level,
            )
            for r in rows
        ]
        changes = [
            explain_change(prev.report, curr.report, prev.run_id, curr.run_id)
            for prev, curr in zip(rows, rows[1:], strict=False)
        ]
        return ScoreHistory(symbol=symbol.upper(), points=points, changes=list(reversed(changes))[:10])

    async def market(self, run_id: str | None) -> MarketOverview:
        run = await self._resolve_run(run_id)
        snapshot = await self.store.snapshots.market_for_run(run.id) if run else None
        if run is None or snapshot is None:
            raise NotFoundError("No completed research run yet. Start a research scan first.")
        return MarketOverview(
            run_id=run.id,
            run_number=run.run_number,
            generated_at=run.completed_at or run.created_at,
            is_synthetic=run.is_synthetic,
            data_source=run.data_source,
            context=MarketContext.model_validate(snapshot.context),
        )

    async def sectors(self, run_id: str | None) -> SectorOverview:
        overview = await self.market(run_id)
        return SectorOverview(
            run_id=overview.run_id,
            run_number=overview.run_number,
            as_of=overview.context.as_of,
            is_synthetic=overview.is_synthetic,
            sectors=overview.context.sectors,
        )

    # ---- weights ------------------------------------------------------------------------------------
    async def list_weights(self) -> list[ResearchWeightSet]:
        return list(await self.store.weights.list_sets())

    async def propose_weights(self, body: WeightSetCreate, user: User | None) -> ResearchWeightSet:
        errors = validate_weights(body.weights)
        if errors:
            raise ValidationFailedError("; ".join(errors))
        return await self.store.weights.create(
            ResearchWeightSet(
                name=body.name,
                version=await self.store.weights.next_version(),
                status="PROPOSED",
                weights=body.weights,
                thresholds=body.thresholds,
                notes=body.notes,
                created_by=user.id if user else None,
            )
        )

    async def approve_weights(self, weight_id: str, user: User | None) -> ResearchWeightSet:
        """Making a set ACTIVE is a deliberate, explicit act. When authentication is on, only an administrator may do it."""
        if self.settings.auth_enabled and (user is None or not user.is_admin):
            raise PermissionDeniedError("Only an administrator can approve scoring weights")
        target = await self.store.weights.get_by_id(weight_id)
        if target is None:
            raise NotFoundError("Weight set not found")
        if target.status == "ACTIVE":
            return target
        await self.store.weights.archive_active()
        target.status, target.approved_by, target.approved_at = "ACTIVE", user.id if user else None, utcnow()
        return await self.store.weights.update(target)

    # ---- sources and universes --------------------------------------------------------------------------
    async def list_sources(self) -> list[ResearchSource]:
        return list(await self.store.sources.list_sources())

    async def update_source(self, source_id: str, values: dict[str, Any]) -> ResearchSource:
        source = await self.store.sources.get_by_id(source_id)
        if source is None:
            raise NotFoundError("Source not found")
        return await self.store.sources.update(source, values)

    async def list_universes(self) -> list[UniverseRead]:
        return [
            UniverseRead(name=name, count=count, note=AS_OF_NOTE if name == UNIVERSE_NAME else None)
            for name, count in await self.store.universe.universes()
        ]

    async def universe(self, name: str) -> UniverseRead:
        rows = await self.store.universe.members(name.upper())
        if not rows:
            raise NotFoundError(f"Unknown universe {name.upper()}")
        names = {}
        for r in rows:
            instrument = await self.store.instruments.get_by_symbol(r.symbol, "NSE")
            names[r.symbol] = instrument.name if instrument else None
        return UniverseRead(
            name=name.upper(),
            count=len(rows),
            note=rows[0].note,
            members=[
                UniverseMemberRead(symbol=r.symbol, sector=r.sector, company=names[r.symbol]) for r in rows
            ],
        )

    async def replace_universe(self, name: str, body: UniverseWrite) -> UniverseRead:
        name = name.strip().upper()
        if name == "CUSTOM":
            raise ValidationFailedError("CUSTOM is reserved for ad-hoc runs")
        unknown = [
            m.symbol
            for m in body.members
            if await self.store.instruments.get_by_symbol(m.symbol, "NSE") is None
        ]
        if unknown:
            raise ValidationFailedError(f"Unknown instrument(s): {', '.join(unknown)}")
        await self.store.universe.clear(name)
        await self.store.universe.add_many(
            [
                ResearchUniverseMember(
                    universe=name,
                    symbol=m.symbol,
                    sector=m.sector,
                    added_on=date.today(),
                    note="Edited through the API",
                )
                for m in body.members
            ]
        )
        return await self.universe(name)

    # ---- export ---------------------------------------------------------------------------------------
    async def export(self, symbol: str, fmt: str, run_id: str | None = None) -> tuple[str, str, str]:
        """(content, media type, file name)."""
        report = await self.report(symbol, run_id)
        stamp = ses.ist_day(report.as_of).isoformat()
        if fmt == "json":
            return (
                report.model_dump_json(indent=2),
                "application/json",
                f"research_{report.symbol}_{stamp}.json",
            )
        if fmt == "csv":
            buffer = io.StringIO()
            w = csv.writer(buffer)
            w.writerow(["section", "field", "value"])
            for field, value in [
                ("symbol", report.symbol),
                ("company", report.company),
                ("as_of", report.as_of.isoformat()),
                ("data_source", report.data_source),
                ("synthetic_data", report.is_synthetic),
                ("research_score", report.research_score),
                ("data_confidence", report.data_confidence),
                ("score_coverage_pct", report.score_coverage_pct),
                ("direction", report.direction),
                ("setup_quality", report.setup_quality),
                ("risk_level", report.risk_level),
            ]:
                w.writerow(["summary", field, value])
            for c in report.score.components:
                w.writerow(
                    [
                        "score_component",
                        c.label,
                        f"{c.points}/{c.max_points}" if c.available else "not assessed",
                    ]
                )
            for label, value in report.labels.items():
                w.writerow(["label", label, value])
            for warning in report.warnings:
                w.writerow(["warning", warning.code, warning.message])
            for i, line in enumerate(report.why_listed, start=1):
                w.writerow(["why_listed", i, line])
            for i, line in enumerate(report.invalidation, start=1):
                w.writerow(["invalidation", i, line])
            for claim in report.verification.claims:
                w.writerow(["verification", claim.key, f"{claim.status}: {claim.detail}"])
            return buffer.getvalue(), "text/csv", f"research_{report.symbol}_{stamp}.csv"
        raise ValidationFailedError("format must be json or csv")


def _broker(name: str):  # noqa: ANN202
    from app.domain.enums import BrokerType

    return BrokerType(name)
