"""research module

Revision ID: 5e87f2db2bd2
Revises: b946a1406ba5
Create Date: 2026-09-22 02:42:12.881030
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision: str = '5e87f2db2bd2'
down_revision: Union[str, None] = 'b946a1406ba5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_sources',
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=24), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('connected', sa.Boolean(), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_sources')),
    sa.UniqueConstraint('key', name=op.f('uq_research_sources_key'))
    )
    op.create_table('research_universe_members',
    sa.Column('universe', sa.String(length=30), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('industry', sa.String(length=80), nullable=True),
    sa.Column('added_on', sa.Date(), nullable=True),
    sa.Column('removed_on', sa.Date(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_universe_members')),
    sa.UniqueConstraint('universe', 'symbol', 'exchange', name=op.f('uq_research_universe_members_universe'))
    )
    op.create_index(op.f('ix_research_universe_members_symbol'), 'research_universe_members', ['symbol'], unique=False)
    op.create_index(op.f('ix_research_universe_members_universe'), 'research_universe_members', ['universe'], unique=False)
    op.create_table('research_weight_sets',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('weights', sa.JSON(), nullable=False),
    sa.Column('thresholds', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('approved_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_research_weight_sets_approved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_research_weight_sets_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_weight_sets'))
    )
    op.create_index(op.f('ix_research_weight_sets_status'), 'research_weight_sets', ['status'], unique=False)
    op.create_index(op.f('ix_research_weight_sets_version'), 'research_weight_sets', ['version'], unique=False)
    op.create_table('research_runs',
    sa.Column('run_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('universe', sa.String(length=30), nullable=False),
    sa.Column('research_type', sa.String(length=20), nullable=False),
    sa.Column('depth', sa.String(length=10), nullable=False),
    sa.Column('as_of', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('is_live', sa.Boolean(), nullable=False),
    sa.Column('market_state', sa.String(length=15), nullable=True),
    sa.Column('data_source', sa.String(length=30), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('weight_set_id', sa.String(length=36), nullable=True),
    sa.Column('requested_symbols', sa.JSON(), nullable=True),
    sa.Column('candidates_scanned', sa.Integer(), nullable=False),
    sa.Column('candidates_analyzed', sa.Integer(), nullable=False),
    sa.Column('sources_checked', sa.Integer(), nullable=False),
    sa.Column('conflicts_found', sa.Integer(), nullable=False),
    sa.Column('started_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('completed_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_research_runs_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['weight_set_id'], ['research_weight_sets.id'], name=op.f('fk_research_runs_weight_set_id_research_weight_sets'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_runs')),
    sa.UniqueConstraint('run_number', name=op.f('uq_research_runs_run_number'))
    )
    op.create_index('ix_research_runs_status_created', 'research_runs', ['status', 'created_at'], unique=False)
    op.create_table('research_agent_outputs',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=True),
    sa.Column('agent', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('data_as_of', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('retrieved_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('structured_data', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], name=op.f('fk_research_agent_outputs_run_id_research_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_agent_outputs'))
    )
    op.create_index('ix_research_agent_outputs_run_symbol', 'research_agent_outputs', ['run_id', 'symbol'], unique=False)
    op.create_table('research_agent_runs',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('agent', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('finished_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('records', sa.Integer(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], name=op.f('fk_research_agent_runs_run_id_research_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_agent_runs')),
    sa.UniqueConstraint('run_id', 'agent', name=op.f('uq_research_agent_runs_run_id'))
    )
    op.create_index(op.f('ix_research_agent_runs_run_id'), 'research_agent_runs', ['run_id'], unique=False)
    op.create_table('research_candidates',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('stage', sa.String(length=10), nullable=False),
    sa.Column('exclusion_reason', sa.Text(), nullable=True),
    sa.Column('initial_score', sa.Float(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], name=op.f('fk_research_candidates_run_id_research_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_candidates')),
    sa.UniqueConstraint('run_id', 'symbol', name=op.f('uq_research_candidates_run_id'))
    )
    op.create_index(op.f('ix_research_candidates_run_id'), 'research_candidates', ['run_id'], unique=False)
    op.create_index(op.f('ix_research_candidates_symbol'), 'research_candidates', ['symbol'], unique=False)
    op.create_table('research_claims',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('claim_key', sa.String(length=40), nullable=False),
    sa.Column('claim_text', sa.String(length=255), nullable=False),
    sa.Column('retrieved_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], name=op.f('fk_research_claims_run_id_research_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_claims'))
    )
    op.create_index('ix_research_claims_run_symbol', 'research_claims', ['run_id', 'symbol'], unique=False)
    op.create_table('research_historical_patterns',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('pattern_key', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('horizon', sa.String(length=16), nullable=False),
    sa.Column('occurrences', sa.Integer(), nullable=False),
    sa.Column('successful', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('avg_return_pct', sa.Float(), nullable=True),
    sa.Column('median_return_pct', sa.Float(), nullable=True),
    sa.Column('avg_return_net_pct', sa.Float(), nullable=True),
    sa.Column('mfe_pct', sa.Float(), nullable=True),
    sa.Column('mae_pct', sa.Float(), nullable=True),
    sa.Column('sample_adequate', sa.Boolean(), nullable=False),
    sa.Column('min_sample', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.String(length=10), nullable=True),
    sa.Column('period_end', sa.String(length=10), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], name=op.f('fk_research_historical_patterns_run_id_research_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_historical_patterns'))
    )
    op.create_index('ix_research_patterns_run_symbol', 'research_historical_patterns', ['run_id', 'symbol'], unique=False)
    op.create_table('research_market_snapshots',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('as_of', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('market_state', sa.String(length=15), nullable=False),
    sa.Column('regime', sa.String(length=16), nullable=False),
    sa.Column('regime_confidence', sa.Float(), nullable=False),
    sa.Column('nifty_price', sa.Float(), nullable=True),
    sa.Column('nifty_change_pct', sa.Float(), nullable=True),
    sa.Column('banknifty_price', sa.Float(), nullable=True),
    sa.Column('banknifty_change_pct', sa.Float(), nullable=True),
    sa.Column('india_vix', sa.Float(), nullable=True),
    sa.Column('advances', sa.Integer(), nullable=True),
    sa.Column('declines', sa.Integer(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], name=op.f('fk_research_market_snapshots_run_id_research_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_market_snapshots')),
    sa.UniqueConstraint('run_id', name=op.f('uq_research_market_snapshots_run_id'))
    )
    op.create_table('research_risk_events',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('metric', sa.String(length=40), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], name=op.f('fk_research_risk_events_run_id_research_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_risk_events'))
    )
    op.create_index(op.f('ix_research_risk_events_code'), 'research_risk_events', ['code'], unique=False)
    op.create_index('ix_research_risk_events_run_symbol', 'research_risk_events', ['run_id', 'symbol'], unique=False)
    op.create_table('research_scores',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('as_of', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('research_score', sa.Float(), nullable=True),
    sa.Column('data_confidence', sa.Float(), nullable=False),
    sa.Column('coverage_pct', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('setup_quality', sa.String(length=10), nullable=False),
    sa.Column('risk_level', sa.String(length=8), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('capped', sa.Boolean(), nullable=False),
    sa.Column('weight_set_id', sa.String(length=36), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('change_pct', sa.Float(), nullable=True),
    sa.Column('rel_volume', sa.Float(), nullable=True),
    sa.Column('atr_pct', sa.Float(), nullable=True),
    sa.Column('vwap', sa.Float(), nullable=True),
    sa.Column('vwap_position', sa.String(length=6), nullable=True),
    sa.Column('initial_score', sa.Float(), nullable=True),
    sa.Column('warning_count', sa.Integer(), nullable=False),
    sa.Column('report', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], name=op.f('fk_research_scores_run_id_research_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['weight_set_id'], ['research_weight_sets.id'], name=op.f('fk_research_scores_weight_set_id_research_weight_sets'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_scores')),
    sa.UniqueConstraint('run_id', 'symbol', name=op.f('uq_research_scores_run_id'))
    )
    op.create_index('ix_research_scores_run_score', 'research_scores', ['run_id', 'research_score'], unique=False)
    op.create_index('ix_research_scores_symbol_asof', 'research_scores', ['symbol', 'as_of'], unique=False)
    op.create_table('research_sector_snapshots',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('sector', sa.String(length=50), nullable=False),
    sa.Column('constituents', sa.Integer(), nullable=False),
    sa.Column('ret_1d_pct', sa.Float(), nullable=True),
    sa.Column('ret_5d_pct', sa.Float(), nullable=True),
    sa.Column('rel_strength_1d', sa.Float(), nullable=True),
    sa.Column('rel_strength_5d', sa.Float(), nullable=True),
    sa.Column('avg_rel_volume', sa.Float(), nullable=True),
    sa.Column('breadth_pct', sa.Float(), nullable=True),
    sa.Column('momentum', sa.Float(), nullable=True),
    sa.Column('trend', sa.String(length=10), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], name=op.f('fk_research_sector_snapshots_run_id_research_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_sector_snapshots'))
    )
    op.create_index(op.f('ix_research_sector_snapshots_run_id'), 'research_sector_snapshots', ['run_id'], unique=False)
    op.create_table('research_score_components',
    sa.Column('score_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=24), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('max_points', sa.Float(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.String(length=12), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['score_id'], ['research_scores.id'], name=op.f('fk_research_score_components_score_id_research_scores'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_score_components'))
    )
    op.create_index(op.f('ix_research_score_components_score_id'), 'research_score_components', ['score_id'], unique=False)
    op.create_table('research_verifications',
    sa.Column('claim_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('sources_checked', sa.Integer(), nullable=False),
    sa.Column('independent_origins', sa.Integer(), nullable=False),
    sa.Column('tolerance_pct', sa.Float(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('source_values', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['research_claims.id'], name=op.f('fk_research_verifications_claim_id_research_claims'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_verifications')),
    sa.UniqueConstraint('claim_id', name=op.f('uq_research_verifications_claim_id'))
    )
    op.create_index(op.f('ix_research_verifications_status'), 'research_verifications', ['status'], unique=False)
    op.drop_constraint(op.f('uq_candles_bar'), 'candles', type_='unique')
    op.create_unique_constraint('uq_candles_bar', 'candles', ['symbol', 'exchange', 'timeframe', 'timestamp', 'source'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_candles_bar', 'candles', type_='unique')
    op.create_unique_constraint(op.f('uq_candles_bar'), 'candles', ['symbol', 'exchange', 'timeframe', 'timestamp'])
    op.drop_table('research_verifications')
    op.drop_table('research_score_components')
    op.drop_table('research_sector_snapshots')
    op.drop_table('research_scores')
    op.drop_table('research_risk_events')
    op.drop_table('research_market_snapshots')
    op.drop_table('research_historical_patterns')
    op.drop_table('research_claims')
    op.drop_table('research_candidates')
    op.drop_table('research_agent_runs')
    op.drop_table('research_agent_outputs')
    op.drop_table('research_runs')
    op.drop_table('research_weight_sets')
    op.drop_table('research_universe_members')
    op.drop_table('research_sources')
    # ### end Alembic commands ###
