"""initial tables

Revision ID: b946a1406ba5
Revises: 
Create Date: 2026-09-18 23:03:36.339739
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision: str = 'b946a1406ba5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candles',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('timeframe', sa.Enum('1m', '5m', '15m', '1h', '1d', name='timeframe', native_enum=False, length=5), nullable=False),
    sa.Column('timestamp', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candles')),
    sa.UniqueConstraint('symbol', 'exchange', 'timeframe', 'timestamp', name='uq_candles_bar')
    )
    op.create_table('daily_pnl',
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('trading_mode', sa.Enum('BACKTEST', 'PAPER', 'SANDBOX', 'LIVE', name='tradingmode', native_enum=False, length=20), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('charges', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('net_pnl', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('trades', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_pnl')),
    sa.UniqueConstraint('trade_date', 'trading_mode', name=op.f('uq_daily_pnl_trade_date'))
    )
    op.create_index(op.f('ix_daily_pnl_trade_date'), 'daily_pnl', ['trade_date'], unique=False)
    op.create_table('instruments',
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('segment', sa.String(length=20), nullable=False),
    sa.Column('exchange_token', sa.String(length=32), nullable=True),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('lot_size', sa.Integer(), nullable=False),
    sa.Column('tick_size', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instruments')),
    sa.UniqueConstraint('symbol', 'exchange', name=op.f('uq_instruments_symbol'))
    )
    op.create_index(op.f('ix_instruments_exchange_token'), 'instruments', ['exchange_token'], unique=False)
    op.create_index(op.f('ix_instruments_symbol'), 'instruments', ['symbol'], unique=False)
    op.create_table('portfolio_snapshots',
    sa.Column('timestamp', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('trading_mode', sa.Enum('BACKTEST', 'PAPER', 'SANDBOX', 'LIVE', name='tradingmode', native_enum=False, length=20), nullable=False),
    sa.Column('equity', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('open_positions', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolio_snapshots'))
    )
    op.create_index('ix_portfolio_snapshots_mode_ts', 'portfolio_snapshots', ['trading_mode', 'timestamp'], unique=False)
    op.create_table('risk_configurations',
    sa.Column('max_risk_per_trade', sa.Numeric(precision=10, scale=6, asdecimal=False), nullable=False),
    sa.Column('max_daily_loss', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('max_trades_per_day', sa.Integer(), nullable=False),
    sa.Column('max_open_positions', sa.Integer(), nullable=False),
    sa.Column('max_position_size', sa.Integer(), nullable=False),
    sa.Column('max_order_value', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('max_consecutive_losses', sa.Integer(), nullable=False),
    sa.Column('max_strategy_drawdown', sa.Numeric(precision=10, scale=6, asdecimal=False), nullable=False),
    sa.Column('close_positions_on_kill_switch', sa.Boolean(), nullable=False),
    sa.Column('kill_switch_active', sa.Boolean(), nullable=False),
    sa.Column('kill_switch_activated_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('kill_switch_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_configurations'))
    )
    op.create_table('system_events',
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Enum('INFO', 'WARNING', 'ERROR', name='eventlevel', native_enum=False, length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('strategy_id', sa.String(length=36), nullable=True),
    sa.Column('order_id', sa.String(length=36), nullable=True),
    sa.Column('symbol', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_events'))
    )
    op.create_index('ix_system_events_created', 'system_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_events_event_type'), 'system_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_system_events_strategy_id'), 'system_events', ['strategy_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('broker_accounts',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('broker_type', sa.Enum('PAPER', 'DHAN', 'ZERODHA', 'FYERS', name='brokertype', native_enum=False, length=20), nullable=False),
    sa.Column('environment', sa.Enum('PAPER', 'SANDBOX', 'LIVE', name='brokerenvironment', native_enum=False, length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('live_armed', sa.Boolean(), nullable=False),
    sa.Column('connection_status', sa.Enum('CONNECTED', 'DISCONNECTED', 'NOT_CONFIGURED', 'UNKNOWN', name='connectionstatus', native_enum=False, length=20), nullable=False),
    sa.Column('last_checked_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_broker_accounts_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_broker_accounts'))
    )
    op.create_index(op.f('ix_broker_accounts_broker_type'), 'broker_accounts', ['broker_type'], unique=False)
    op.create_index(op.f('ix_broker_accounts_user_id'), 'broker_accounts', ['user_id'], unique=False)
    op.create_table('strategies',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('broker_account_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('strategy_type', sa.Enum('EMA_CROSSOVER', 'VWAP', 'BREAKOUT', name='strategytype', native_enum=False, length=30), nullable=False),
    sa.Column('status', sa.Enum('STOPPED', 'RUNNING', 'ERROR', name='strategystatus', native_enum=False, length=20), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('timeframe', sa.Enum('1m', '5m', '15m', '1h', '1d', name='timeframe', native_enum=False, length=5), nullable=False),
    sa.Column('capital', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('risk_per_trade', sa.Numeric(precision=10, scale=6, asdecimal=False), nullable=False),
    sa.Column('stop_loss_pct', sa.Numeric(precision=10, scale=6, asdecimal=False), nullable=False),
    sa.Column('target_pct', sa.Numeric(precision=10, scale=6, asdecimal=False), nullable=True),
    sa.Column('allow_short', sa.Boolean(), nullable=False),
    sa.Column('trading_mode', sa.Enum('BACKTEST', 'PAPER', 'SANDBOX', 'LIVE', name='tradingmode', native_enum=False, length=20), nullable=False),
    sa.Column('last_candle_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('last_evaluated_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('last_signal_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['broker_account_id'], ['broker_accounts.id'], name=op.f('fk_strategies_broker_account_id_broker_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_strategies_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategies')),
    sa.UniqueConstraint('name', name=op.f('uq_strategies_name'))
    )
    op.create_index(op.f('ix_strategies_status'), 'strategies', ['status'], unique=False)
    op.create_index(op.f('ix_strategies_symbol'), 'strategies', ['symbol'], unique=False)
    op.create_index(op.f('ix_strategies_user_id'), 'strategies', ['user_id'], unique=False)
    op.create_table('backtests',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('strategy_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('strategy_type', sa.Enum('EMA_CROSSOVER', 'VWAP', 'BREAKOUT', name='strategytype', native_enum=False, length=30), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('timeframe', sa.Enum('1m', '5m', '15m', '1h', '1d', name='timeframe', native_enum=False, length=5), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('initial_capital', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='backteststatus', native_enum=False, length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('equity_curve', sa.JSON(), nullable=True),
    sa.Column('completed_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_backtests_strategy_id_strategies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_backtests_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backtests'))
    )
    op.create_index(op.f('ix_backtests_status'), 'backtests', ['status'], unique=False)
    op.create_index(op.f('ix_backtests_strategy_id'), 'backtests', ['strategy_id'], unique=False)
    op.create_table('orders',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('broker_account_id', sa.String(length=36), nullable=True),
    sa.Column('strategy_id', sa.String(length=36), nullable=True),
    sa.Column('broker_type', sa.Enum('PAPER', 'DHAN', 'ZERODHA', 'FYERS', name='brokertype', native_enum=False, length=20), nullable=False),
    sa.Column('broker_order_id', sa.String(length=64), nullable=True),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='orderside', native_enum=False, length=10), nullable=False),
    sa.Column('order_type', sa.Enum('MARKET', 'LIMIT', 'SL', 'SL-M', name='ordertype', native_enum=False, length=10), nullable=False),
    sa.Column('product_type', sa.Enum('INTRADAY', 'DELIVERY', name='producttype', native_enum=False, length=20), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('filled_quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=True),
    sa.Column('trigger_price', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=True),
    sa.Column('average_fill_price', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=True),
    sa.Column('target', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'SUBMITTED', 'OPEN', 'TRIGGER_PENDING', 'PARTIALLY_FILLED', 'FILLED', 'CANCELLED', 'REJECTED', 'FAILED', 'EXPIRED', name='orderstatus', native_enum=False, length=20), nullable=False),
    sa.Column('status_message', sa.Text(), nullable=True),
    sa.Column('trading_mode', sa.Enum('BACKTEST', 'PAPER', 'SANDBOX', 'LIVE', name='tradingmode', native_enum=False, length=20), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'STRATEGY', 'RISK_EXIT', 'KILL_SWITCH', name='ordersource', native_enum=False, length=20), nullable=False),
    sa.Column('exit_reason', sa.Enum('SIGNAL', 'STOP_LOSS', 'TARGET', 'MANUAL', 'KILL_SWITCH', 'END_OF_DATA', name='exitreason', native_enum=False, length=20), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['broker_account_id'], ['broker_accounts.id'], name=op.f('fk_orders_broker_account_id_broker_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_orders_strategy_id_strategies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_orders_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    op.create_index(op.f('ix_orders_broker_order_id'), 'orders', ['broker_order_id'], unique=False)
    op.create_index('ix_orders_status_created', 'orders', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_orders_strategy_id'), 'orders', ['strategy_id'], unique=False)
    op.create_index('ix_orders_symbol_created', 'orders', ['symbol', 'created_at'], unique=False)
    op.create_table('positions',
    sa.Column('strategy_id', sa.String(length=36), nullable=True),
    sa.Column('broker_account_id', sa.String(length=36), nullable=True),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('side', sa.Enum('LONG', 'SHORT', name='positionside', native_enum=False, length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('average_entry_price', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('last_price', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('charges_accrued', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=True),
    sa.Column('target', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='positionstatus', native_enum=False, length=10), nullable=False),
    sa.Column('trading_mode', sa.Enum('BACKTEST', 'PAPER', 'SANDBOX', 'LIVE', name='tradingmode', native_enum=False, length=20), nullable=False),
    sa.Column('opened_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('closed_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['broker_account_id'], ['broker_accounts.id'], name=op.f('fk_positions_broker_account_id_broker_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_positions_strategy_id_strategies'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_positions'))
    )
    op.create_index('ix_positions_status_symbol', 'positions', ['status', 'symbol'], unique=False)
    op.create_index(op.f('ix_positions_strategy_id'), 'positions', ['strategy_id'], unique=False)
    op.create_table('signals',
    sa.Column('strategy_id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=True),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('signal_type', sa.Enum('BUY', 'SELL', 'HOLD', name='signaltype', native_enum=False, length=10), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('indicators', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('GENERATED', 'EXECUTED', 'REJECTED', 'IGNORED', name='signalstatus', native_enum=False, length=20), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('candle_time', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_signals_strategy_id_strategies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signals'))
    )
    op.create_index(op.f('ix_signals_order_id'), 'signals', ['order_id'], unique=False)
    op.create_index('ix_signals_strategy_created', 'signals', ['strategy_id', 'created_at'], unique=False)
    op.create_table('strategy_parameters',
    sa.Column('strategy_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_strategy_parameters_strategy_id_strategies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategy_parameters')),
    sa.UniqueConstraint('strategy_id', 'key', name=op.f('uq_strategy_parameters_strategy_id'))
    )
    op.create_index(op.f('ix_strategy_parameters_strategy_id'), 'strategy_parameters', ['strategy_id'], unique=False)
    op.create_table('backtest_trades',
    sa.Column('backtest_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('side', sa.Enum('LONG', 'SHORT', name='positionside', native_enum=False, length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('entry_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('exit_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('gross_pnl', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('charges', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('net_pnl', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('exit_reason', sa.Enum('SIGNAL', 'STOP_LOSS', 'TARGET', 'MANUAL', 'KILL_SWITCH', 'END_OF_DATA', name='exitreason', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtests.id'], name=op.f('fk_backtest_trades_backtest_id_backtests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backtest_trades'))
    )
    op.create_index(op.f('ix_backtest_trades_backtest_id'), 'backtest_trades', ['backtest_id'], unique=False)
    op.create_table('order_events',
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_events_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_events'))
    )
    op.create_index(op.f('ix_order_events_order_id'), 'order_events', ['order_id'], unique=False)
    op.create_table('trades',
    sa.Column('position_id', sa.String(length=36), nullable=True),
    sa.Column('strategy_id', sa.String(length=36), nullable=True),
    sa.Column('exit_order_id', sa.String(length=36), nullable=True),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('side', sa.Enum('LONG', 'SHORT', name='positionside', native_enum=False, length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('entry_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('exit_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('gross_pnl', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('charges', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('net_pnl', sa.Numeric(precision=18, scale=4, asdecimal=False), nullable=False),
    sa.Column('exit_reason', sa.Enum('SIGNAL', 'STOP_LOSS', 'TARGET', 'MANUAL', 'KILL_SWITCH', 'END_OF_DATA', name='exitreason', native_enum=False, length=20), nullable=False),
    sa.Column('trading_mode', sa.Enum('BACKTEST', 'PAPER', 'SANDBOX', 'LIVE', name='tradingmode', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['exit_order_id'], ['orders.id'], name=op.f('fk_trades_exit_order_id_orders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name=op.f('fk_trades_position_id_positions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_trades_strategy_id_strategies'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trades'))
    )
    op.create_index('ix_trades_exit_time', 'trades', ['exit_time'], unique=False)
    op.create_index(op.f('ix_trades_position_id'), 'trades', ['position_id'], unique=False)
    op.create_index('ix_trades_strategy_exit', 'trades', ['strategy_id', 'exit_time'], unique=False)
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_index('ix_trades_strategy_exit', table_name='trades')
    op.drop_index(op.f('ix_trades_position_id'), table_name='trades')
    op.drop_index('ix_trades_exit_time', table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_order_events_order_id'), table_name='order_events')
    op.drop_table('order_events')
    op.drop_index(op.f('ix_backtest_trades_backtest_id'), table_name='backtest_trades')
    op.drop_table('backtest_trades')
    op.drop_index(op.f('ix_strategy_parameters_strategy_id'), table_name='strategy_parameters')
    op.drop_table('strategy_parameters')
    op.drop_index('ix_signals_strategy_created', table_name='signals')
    op.drop_index(op.f('ix_signals_order_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_positions_strategy_id'), table_name='positions')
    op.drop_index('ix_positions_status_symbol', table_name='positions')
    op.drop_table('positions')
    op.drop_index('ix_orders_symbol_created', table_name='orders')
    op.drop_index(op.f('ix_orders_strategy_id'), table_name='orders')
    op.drop_index('ix_orders_status_created', table_name='orders')
    op.drop_index(op.f('ix_orders_broker_order_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_backtests_strategy_id'), table_name='backtests')
    op.drop_index(op.f('ix_backtests_status'), table_name='backtests')
    op.drop_table('backtests')
    op.drop_index(op.f('ix_strategies_user_id'), table_name='strategies')
    op.drop_index(op.f('ix_strategies_symbol'), table_name='strategies')
    op.drop_index(op.f('ix_strategies_status'), table_name='strategies')
    op.drop_table('strategies')
    op.drop_index(op.f('ix_broker_accounts_user_id'), table_name='broker_accounts')
    op.drop_index(op.f('ix_broker_accounts_broker_type'), table_name='broker_accounts')
    op.drop_table('broker_accounts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_events_strategy_id'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_event_type'), table_name='system_events')
    op.drop_index('ix_system_events_created', table_name='system_events')
    op.drop_table('system_events')
    op.drop_table('risk_configurations')
    op.drop_index('ix_portfolio_snapshots_mode_ts', table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    op.drop_index(op.f('ix_instruments_symbol'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_exchange_token'), table_name='instruments')
    op.drop_table('instruments')
    op.drop_index(op.f('ix_daily_pnl_trade_date'), table_name='daily_pnl')
    op.drop_table('daily_pnl')
    op.drop_table('candles')
    # ### end Alembic commands ###
